baseURL = '/'
languageCode = 'en-us'
title = 'towaos blog'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[pagination]
pagerSize = 10
path = "page"

[params]
author = "towaos"
description = "Let's Gooo!!"
avatar = "/images/towaos_icon.png"
github = "towaos"
url = "https://blog.towaos.com"
favicon = "/images/towaos.png"
headerIcon = "/images/towaos_icon.png"
userStatusEmoji = "😀"
lastmod = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "github"
    noClasses = false

ignoreLogs = ['warning-goldmark-raw-html']